{
  "formatVersion": "1.1",
  "component": {
    "group": "com.launchkey.android.authenticator.sdk",
    "module": "lk-auth-sdk",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "gddo6v6bmnfzjldcy2pyyo3vci"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lk-auth-sdk-4.10.0.aar",
          "url": "lk-auth-sdk-4.10.0.aar",
          "size": 3753406,
          "sha512": "6fe51fe0d7521221c948b1613722696d4dbdf0e04d9fa626d384048eac43ec1e68ffce46cfd1ad14f5a0577106975af0624d728f1ffcaa301382d93b365cf4d6",
          "sha256": "ed6c4916c9ac293ae93cf6bf20435e4887e28706783188bb72e5e40521124045",
          "sha1": "10700dbd1e8f722cbf8851db9f84f0121a61d558",
          "md5": "bac65612531b3d7ca093a4884c33f783"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "24.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "24.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "design",
          "version": {
            "requires": "24.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wearable",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.launchkey.android.authenticator.sdk",
          "module": "lk-auth-sdk-core",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lk-auth-sdk-4.10.0.aar",
          "url": "lk-auth-sdk-4.10.0.aar",
          "size": 3753406,
          "sha512": "6fe51fe0d7521221c948b1613722696d4dbdf0e04d9fa626d384048eac43ec1e68ffce46cfd1ad14f5a0577106975af0624d728f1ffcaa301382d93b365cf4d6",
          "sha256": "ed6c4916c9ac293ae93cf6bf20435e4887e28706783188bb72e5e40521124045",
          "sha1": "10700dbd1e8f722cbf8851db9f84f0121a61d558",
          "md5": "bac65612531b3d7ca093a4884c33f783"
        }
      ]
    }
  ]
}
