{
  "formatVersion": "1.1",
  "component": {
    "group": "com.launchkey.android.authenticator.sdk",
    "module": "lk-auth-sdk",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "mnic5caryvbpjcs3yjho3g3gnm"
    }
  },
  "variants": [
    {
      "name": "fips_offReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "lk-auth-sdk-5.1.0.aar",
          "url": "lk-auth-sdk-5.1.0.aar",
          "size": 4253056,
          "sha512": "a3869f4258e3fa61d092984ffbcd520487cc70dc0a5d1c9394cb3fbad29dd37ec19b11bf6b0adc171f7a7ff101258fa27fa896614c602c93d7732bf5c35e4bf2",
          "sha256": "5ebfb1b4f227e17fdf69ef8f44dd63a7da4dabbfc7aac5a5bdf117f4d4ddf1a5",
          "sha1": "bfb7d0c1c444929a88f87d7e2a473f98b09d8edb",
          "md5": "ed81855132b3226226245b23acaaaf59"
        }
      ]
    },
    {
      "name": "fips_offReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.2.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wearable",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.launchkey.android.authenticator.sdk",
          "module": "lk-auth-sdk-core",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lk-auth-sdk-5.1.0.aar",
          "url": "lk-auth-sdk-5.1.0.aar",
          "size": 4253056,
          "sha512": "a3869f4258e3fa61d092984ffbcd520487cc70dc0a5d1c9394cb3fbad29dd37ec19b11bf6b0adc171f7a7ff101258fa27fa896614c602c93d7732bf5c35e4bf2",
          "sha256": "5ebfb1b4f227e17fdf69ef8f44dd63a7da4dabbfc7aac5a5bdf117f4d4ddf1a5",
          "sha1": "bfb7d0c1c444929a88f87d7e2a473f98b09d8edb",
          "md5": "ed81855132b3226226245b23acaaaf59"
        }
      ]
    }
  ]
}
