{
  "formatVersion": "1.1",
  "component": {
    "group": "com.launchkey.android.authenticator.sdk",
    "module": "lk-auth-sdk",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "di3q3r6fgzh6hfeyzq765nsa7y"
    }
  },
  "variants": [
    {
      "name": "fips_offReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "lk-auth-sdk-5.0.0.aar",
          "url": "lk-auth-sdk-5.0.0.aar",
          "size": 3451695,
          "sha512": "39be191a59d9c123797ce308ec17011a947cdaa80aa0edf29cb7721d75d6ea507191b17c0ea53a40d210a4f32e8a0e0371ba7c51b4153c10451d53b05dd08b37",
          "sha256": "c64b0f96d4e30f98fa6bdad82e6a080454b001841e2a6338d22f31402126c0b6",
          "sha1": "90e9365ff9d826cbc911787af870af69de956d7a",
          "md5": "1dcf99438f303c11540dfd9c8b2b979a"
        }
      ]
    },
    {
      "name": "fips_offReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.2.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wearable",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.launchkey.android.authenticator.sdk",
          "module": "lk-auth-sdk-core",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lk-auth-sdk-5.0.0.aar",
          "url": "lk-auth-sdk-5.0.0.aar",
          "size": 3451695,
          "sha512": "39be191a59d9c123797ce308ec17011a947cdaa80aa0edf29cb7721d75d6ea507191b17c0ea53a40d210a4f32e8a0e0371ba7c51b4153c10451d53b05dd08b37",
          "sha256": "c64b0f96d4e30f98fa6bdad82e6a080454b001841e2a6338d22f31402126c0b6",
          "sha1": "90e9365ff9d826cbc911787af870af69de956d7a",
          "md5": "1dcf99438f303c11540dfd9c8b2b979a"
        }
      ]
    }
  ]
}
